### ISSUE TITLE
Snapshot delete tooltip reopens

### ISSUE THREAD

**Issue by fmalcher** [bitfocusas/product-snapshot#8]
After deleting a snapshot, the "confirm delete" tooltip pops up again when selecting another snapshot

### Reproduction

- Create 2 or more snapshots
- select one of them
- click "delete", click "I confirm". The delete button becomes inactive
- select another snapshot
- the delete tooltip opens again (probably never closed)

Version: v1.0.2.959

**Comment by willosof** [comment]
fixed
